# Define the name of the GitHub Actions workflow
name: CI

# Specify the events that trigger this workflow (push and pull_request to the main branch)
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define the jobs that this workflow consists of
jobs:
  pre-hook:
    # Specify the operating systems to run this job (All platforms: Linux, macOS, Windows)
    runs-on: ${{ matrix.os }}

    # Define a strategy for running this job on different platforms
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    # Define the individual steps to be executed as part of this job
    steps:
      # Step 1: Run pytest on the test files
      - name: Run pytest on the contents of the tests folder
        run: pytest "sprint-4/tests/"

  continuous-integration:
    # Specify the operating systems to run this job (All platforms: Linux, macOS, Windows)
    runs-on: ${{ matrix.os }}

    # Define a strategy for running this job on different platforms
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    # Define a strategy for running this job with different Python versions
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.10]

    # Define the individual steps to be executed as part of this job
    steps:
      # Additional steps for the continuous integration process
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -r requirements.txt
