# Define the name of the GitHub Actions workflow
name: CI

# Specify the events that trigger this workflow (push and pull_request to the main branch)
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define the jobs that this workflow consists of
jobs:
  continuous-integration:
    # Specify the operating system to run this job (Windows in this case)
    runs-on: windows-latest # You can use different OS types [ubuntu-latest, macos-latest, windows-latest]

    # Define a strategy for running this job with different Python versions
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.10]

    # Define the individual steps to be executed as part of this job
    steps:
      # Step 1: Checkout the source code of the repository using 'actions/checkout' action
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Update pip to the latest version using 'python -m pip install --upgrade pip'
      - name: Update pip
        run: python -m pip install --upgrade pip

      # Step 3: Install project dependencies listed in 'requirements.txt' using 'pip install'
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Step 4: Run pytest on the specified test file 'Sprint 2/Implemented Features/Backend/test_initial.py'
      - name: Run pytest on test_initial.py
        run: pytest "sprint-4/tests/
