name: CI

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  lint-and-test:
    runs-on: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: [3.7, 3.8, 3.9, 3.10]

      - name: Install dependencies
        run: pip install -r requirements.txt  # Replace with your requirements file if needed

      - name: Run flake8
        run: flake8

      - name: Run pytest
        run: pytest
