name: CI

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  lint-and-test:
    runs-on: windows-latest # Use this set to test on various systems [ubuntu-latest, macos-latest, windows-latest]

    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.10]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install -r requirements.txt  
      
      - name: Run pytest on test_initial.py
        run: pytest "Sprint 2/Implemented Features/Backend/test_initial.py"
